pipeline {
    
        stage('Preparation') { // for display purposes
          // Get some code from a GitHub repository
          git 'https://github.com/kotachandrasekhar/simple-java-maven-app.git'
          // Get the Maven tool.
          // ** NOTE: This 'M3' Maven tool must be configured
          // **       in the global configuration.           
          mvnHome = tool 'M3'
       }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
       }     
        stage('Results') {
           junit '**/target/surefire-reports/TEST-*.xml'
           archiveArtifacts 'target/*.jar'
       }
       stage('Post') {
          //gsutil cp 'target/*.jar' 'gs://jenkins--bucket'
        googleStorageUpload bucket: 'gs://expbuck', credentialsId: 'project-01', pattern: 'target/*.jar'
       }   
}
